version: '3.4'
services:

  {% if cookiecutter.participant_type == "microengine" %}
  {% if cookiecutter.microengine__has_backend == "true" %}
  {{ cookiecutter.participant_name_slug }}backend:
    image: "{{ cookiecutter.project_slug }}-backend"
    ports:
      - 8888:8080
  {% endif %}
  {% endif %}
 
  test_{{ cookiecutter.participant_name_slug }}:
    {% if cookiecutter.microengine__has_worker == "true" %}
    image: "polyswarm/polyswarm-client"
    {% else %}
    image: "{{ cookiecutter.project_slug }}"
    {% endif %}
    {% if cookiecutter.participant_type == "microengine" %}
    {% if cookiecutter.microengine__has_backend == "true" %}
    depends_on:
      - {{ cookiecutter.project_slug }}backend
    {% endif %}
    {% endif %}
    environment:
      - PYTHONUNBUFFERED=1
      - KEYFILE=docker/{{ cookiecutter.participant_type}}_keyfile
      - PASSWORD=password
    command:
      - "dockerize"
      - "-wait"
      - "tcp://polyswarmd:31337"
      - "-timeout"
      - "1000s"
      - "{{ cookiecutter.participant_type}}"
      - "--log"
      - "info"
      - "--polyswarmd-addr"
      - "polyswarmd:31337"
      - "--insecure-transport"
      - "--testing"
      - "10"
      - "--chains"
      - "side"
    {% if cookiecutter.microengine__has_worker == "true" %}
      - "--backend"
      - "producer"
    {% else %}
      - "--backend"
      - "{{ cookiecutter.package_slug }}"
    {% endif %}

 {% if cookiecutter.microengine__has_worker == "true" %}
  test_{{ cookiecutter.participant_name_slug }}_worker:
    image: "{{ cookiecutter.project_slug }}"
    depends_on:
      - "test_{{ cookiecutter.project_slug }}"
    environment:
      - PYTHONUNBUFFERED=1
    command:
      - "dockerize"
      - "-wait"
      - "tcp://polyswarmd:31337"
      - "-timeout"
      - "1000s"
      - "worker"
      - "--log"
      - "info"
      - "--redis_addr"
      - "redis:6379"
      - "--backend"
      - "{{ cookiecutter.package_slug }}"
  {% endif %}

  test_deposit-{{ cookiecutter.participant_name_slug }}:
    image: "polyswarm/polyswarm-client"
    environment:
      - PYTHONUNBUFFERED=1
      - KEYFILE=docker/{{ cookiecutter.participant_type}}_keyfile
      - PASSWORD=password
    command:
      - "dockerize"
      - "-wait"
      - "tcp://polyswarmd:31337"
      - "-timeout"
      - "1000s"
      - "balancemanager"
      - "--log"
      - "info"
      - "deposit"
      - "--polyswarmd-addr"
      - "polyswarmd:31337"
      - "--insecure-transport"
      - "100000"

networks:
  default:
    external:
      name: orchestration_default
