version: '3.4'
services:

  {% if cookiecutter.participant_type == "microengine" %}
  {% if cookiecutter.microengine__has_backend == "true" %}
  {{ cookiecutter.participant_name_slug }}backend:
    image: "{{ cookiecutter.project_slug }}-backend"
    ports:
      - 8888:8080
  {% endif %}
  {% endif %}

  test_{{ cookiecutter.participant_name_slug }}:
    image: "{{ cookiecutter.project_slug }}"
    {% if cookiecutter.participant_type == "microengine" %}
    {% if cookiecutter.microengine__has_backend == "true" %}
    depends_on:
      - {{ cookiecutter.project_slug }}backend
    {% endif %}
    {% endif %}
    environment:
      - PYTHON_UNBUFFERED=1
    command: ["tox"]
